### ISSUE TITLE
[Bug] Tooltip duplicating

### ISSUE THREAD

**Issue by Squimbert** [fang2hou/ElvUI_WindTools#311] opened 2023-01-28 20:47 UTC
**Describe the bug**

Tooltip in talents frame keeps duplicating when hovering over a talent.

**To Reproduce**

1. Open talent frame with ElvUI and Windtools enabled.
2. Hover cursor over a talent.

**Expected behavior**

Hovering over a talent should only show 1 tooltip, not repeated duplicates.

**Screenshots**

https://imgur.com/a/4eVrE5E

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.22
 - ElvUI Version 13.23
 - WoW Build 10.0.5 (47871)

**Additional context**

I tested this with only ElvUI enabled and the bug was not apparent.  But when I enabled Windtools as well, the bug happened.

**Comment by fang2hou** [comment] 2023-01-29 04:21
did you test with `/wtdebug on`?

**Comment by Squimbert** [comment] 2023-01-29 22:51
yes i did. and it seems to happen most when i hover over a talent, close and reopen talent frame, then hover over it again.

**Comment by fang2hou** [comment] 2023-02-01 08:59
Cannot reproduce your issue and there is no more other report of this.
Please add some screenshot of your addon list, you should test it with **ONLY** WindTools and elvui enabled.

**Comment by fang2hou** [comment] 2023-02-14 08:15
Close the issue there is no more contextual information provided.

**Closed by fang2hou** 2023-02-14 08:15 UTC
Labels: bug
